export enum BodyMaleFront {
  Head = 'headMB',
  Neck = 'neckMB',
  Chest = 'chestMB',
  Abdomen = 'abdomenMB',
  Pelvis = 'pelvisMB',
  ShoulderRt = 'shoulderRtMB',
  ShoulderLt = 'shoulderLtMB',
  ArmRt = 'armRtMB',
  ArmLt = 'armLtMB',
  ElbowRt = 'elbowRtMB',
  ElbowLt = 'elbowLtMB',
  ForearmRt = 'forearmRtMB',
  ForearmLt = 'forearmLtMB',
  WristRt = 'wristRtMB',
  WristLt = 'wristLtMB',
  HandRt = 'handRtMB',
  HandLt = 'handLtMB',
  ThighRt = 'thighRtMB',
  ThighLt = 'thighLtMB',
  KneeRt = 'kneeRtMB',
  KneeLt = 'kneeLtMB',
  LegRt = 'legRtMB',
  LegLt = 'legLtMB',
  AnkleRt = 'ankleRtMB',
  AnkleLt = 'ankleLtMB',
  FootRt = 'footRtMB',
  FootLt = 'footLtMB',
}

export enum BodyMaleBack {
  Head = 'headMB',
  Neck = 'neckMB',
  Back = 'backMB',
  Loin = 'loinMB',
  Buttocks = 'buttocksMB',
  ShoulderRt = 'shoulderRtMB',
  ShoulderLt = 'shoulderLtMB',
  ArmRt = 'armRtMB',
  ArmLt = 'armLtMB',
  ElbowRt = 'elbowRtMB',
  ElbowLt = 'elbowLtMB',
  ForearmRt = 'forearmRtMB',
  ForearmLt = 'forearmLtMB',
  WristRt = 'wristRtMB',
  WristLt = 'wristLtMB',
  HandRt = 'handRtMB',
  HandLt = 'handLtMB',
  HamstringRt = 'hamstringRtMB',
  HamstringLt = 'hamstringLtMB',
  CalfRt = 'calfRtMb',
  CalfLt = 'CalfLtMB',
  KneeRt = 'kneeRtMB',
  KneeLt = 'kneeLtMB',
  LegRt = 'legRtMB',
  LegLt = 'legLtMB',
  AnkleRt = 'ankleRtMB',
  AnkleLt = 'ankleLtMB',
  SoleRt = 'soleRtMB',
  SoleLt = 'soleLtMB',
  FootRt = 'footRtMB',
  FootLt = 'footLtMB',
}



