export enum BodyMaleFront {
  Head = 'Head',
  Neck = 'Neck',
  Chest = 'Chest',
  Abdomen = 'Abdomen',
  Pelvis = 'Pelvis',
  ShoulderRt = 'Shoulder [Rt]',
  ShoulderLt = 'Shoulder [Lt]',
  ArmRt = 'Arm [Rt]',
  ArmLt = 'Arm [Lt]',
  ElbowRt = 'Elbow [Rt]',
  ElbowLt = 'Elbow [Lt]',
  ForearmRt = 'Forearm [Rt]',
  ForearmLt = 'Forearm [Lt]',
  WristRt = 'Wrist [Rt]',
  WristLt = 'Wrist [Lt]',
  HandRt = 'Hand [Rt]',
  HandLt = 'Hand [Lt]',
  ThighRt = 'Thigh [Rt]',
  ThighLt = 'Thigh [Lt]',
  KneeRt = 'Knee [Rt]',
  KneeLt = 'Knee [Lt]',
  LegRt = 'Leg [Rt]',
  LegLt = 'Leg [Lt]',
  AnkleRt = 'Ankle [Rt]',
  AnkleLt = 'Ankle [Lt]',
  FootRt = 'Foot [Rt]',
  FootLt = 'Foot [Lt]',
}

export enum BodyFemaleFront {
  Head = 'Head',
  Neck = 'Neck',
  Chest = 'Chest',
  Breasts = 'Breasts',
  Abdomen = 'Abdomen',
  Pelvis = 'Pelvis',
  ShoulderRt = 'Shoulder [Rt]',
  ShoulderLt = 'Shoulder [Lt]',
  ArmRt = 'Arm [Rt]',
  ArmLt = 'Arm [Lt]',
  ElbowRt = 'Elbow [Rt]',
  ElbowLt = 'Elbow [Lt]',
  ForearmRt = 'Forearm [Rt]',
  ForearmLt = 'Forearm [Lt]',
  WristRt = 'Wrist [Rt]',
  WristLt = 'Wrist [Lt]',
  HandRt = 'Hand [Rt]',
  HandLt = 'Hand [Lt]',
  ThighRt = 'Thigh [Rt]',
  ThighLt = 'Thigh [Lt]',
  KneeRt = 'Knee [Rt]',
  KneeLt = 'Knee [Lt]',
  LegRt = 'Leg [Rt]',
  LegLt = 'Leg [Lt]',
  AnkleRt = 'Ankle [Rt]',
  AnkleLt = 'Ankle [Lt]',
  FootRt = 'Foot [Rt]',
  FootLt = 'Foot [Lt]',
}

export enum BodyMaleBack {
  Head = 'Head [Back]',
  Neck = 'Neck [Back]',
  Back = 'Back',
  Loin = 'Loin',
  Buttocks = 'Buttocks',
  ShoulderRt = 'Shoulder [Back] [Rt]',
  ShoulderLt = 'Shoulder [Back] [Lt]',
  ArmRt = 'Arm [Back] [Rt]',
  ArmLt = 'Arm [Back] [Lt]',
  ElbowRt = 'Elbow [Back] [Rt]',
  ElbowLt = 'Elbow [Back] [Lt]',
  ForearmRt = 'Forearm [Back] [Rt]',
  ForearmLt = 'Forearm [Back] [Lt]',
  WristRt = 'Wrist [Back] [Rt]',
  WristLt = 'Wrist [Back] [Lt]',
  HandRt = 'Hand [Back] [Rt]',
  HandLt = 'Hand [Back] [Lt]',
  HamstringRt = 'Hamstring [Rt]',
  HamstringLt = 'Hamstring [Lt]',
  CalfRt = 'Calf [Rt]',
  CalfLt = 'Calf [Lt]',
  KneeRt = 'Knee [Back] [Rt]',
  KneeLt = 'Knee [Back] [Lt]',
  LegRt = 'Leg [Back] [Rt]',
  LegLt = 'Leg [Back] [Lt]',
  AnkleRt = 'Ankle [Back] [Rt]',
  AnkleLt = 'Ankle [Back] [Lt]',
  SoleRt = 'Sole [Rt]',
  SoleLt = 'Sole [Lt]',
  FootRt = 'Foot [Back] [Rt]',
  FootLt = 'Foot [Back] [Lt]',
}

export enum BodyFemaleBack {
  Head = 'Head [Back]',
  Neck = 'Neck [Back]',
  Back = 'Back',
  Loin = 'Loin',
  Buttocks = 'Buttocks',
  ShoulderRt = 'Shoulder [Back] [Rt]',
  ShoulderLt = 'Shoulder [Back] [Lt]',
  ArmRt = 'Arm [Back] [Rt]',
  ArmLt = 'Arm [Back] [Lt]',
  ElbowRt = 'Elbow [Back] [Rt]',
  ElbowLt = 'Elbow [Back] [Lt]',
  ForearmRt = 'Forearm [Back] [Rt]',
  ForearmLt = 'Forearm [Back] [Lt]',
  WristRt = 'Wrist [Back] [Rt]',
  WristLt = 'Wrist [Back] [Lt]',
  HandRt = 'Hand [Back] [Rt]',
  HandLt = 'Hand [Back] [Lt]',
  HamstringRt = 'Hamstring [Rt]',
  HamstringLt = 'Hamstring [Lt]',
  CalfRt = 'Calf [Rt]',
  CalfLt = 'Calf [Lt]',
  KneeRt = 'Knee [Back] [Rt]',
  KneeLt = 'Knee [Back] [Lt]',
  LegRt = 'Leg [Back] [Rt]',
  LegLt = 'Leg [Back] [Lt]',
  AnkleRt = 'Ankle [Back] [Rt]',
  AnkleLt = 'Ankle [Back] [Lt]',
  SoleRt = 'Sole [Rt]',
  SoleLt = 'Sole [Lt]',
  FootRt = 'Foot [Back] [Rt]',
  FootLt = 'Foot [Back] [Lt]',
}

export enum Skeleton {
  Skull = 'Skull',
  Spine = 'Spine',
  Sacrum = 'Sacrum',
  Pelvis = 'Pelvis',
  Ribs = 'Ribs',
  Sternum = 'Sternum',
  ClavicleRt = 'Clavicle [Rt]',
  ClavicleLt = 'Clavicle [Lt]',
  ScapulaRt = 'Scapular [Rt]',
  ScapulaLt = 'Scapula [Lt]',
  HumerusRt = 'Humerus [Rt]',
  HumerusLt = 'Humerus [Lt]',
  RadiusRt = 'Radius [Rt]',
  RadiusLt = 'Radius [Lt]',
  UlnaRt = 'Ulna [Rt]',
  UlnaLt = 'Ulna [Lt]',
  HandRt = 'Hand [Rt]',
  HandLt = 'Hand [Lt]',
  FemurRt = 'Femur [Rt]',
  FemurLt = 'Femur [Lt]',
  PatellaRt = 'Patella [Rt]',
  PatellaLt = 'Patella [Lt]',
  TibiaRt = 'Tibia [Rt]',
  TibiaLt = 'Tibia [Lt]',
  FibulaRt = 'Fibula [Rt]',
  FibulaLt = 'Fibula [Lt]',
  FootRt = 'Foot [Rt]',
  FootLt = 'Foot [Lt]',
  CarpalsRt = 'Carpals [Rt]',
  CarpalsLt = 'Carpals [Lt]',
  MetacarpalsRt = 'Metacarpals [Rt]',
  MetacarpalsLt = 'Metacarpals [Lt]',
  HandPhalangesRt = 'Hand Phalanges [Rt]',
  HandPhalangesLt = 'Hand Phalanges [Lt]',
  CalcaneusRt = 'Calcaneus [Rt]',
  CalcaneusLt = 'Calcaneus [Lt]',
  TalusRt = 'Talus [Rt]',
  TalusLt = 'Talus [Lt]',
  TarsalsRt = 'Tarsals [Rt]',
  TarsalsLt = 'Tarsals [Lt]',
  MetatarsalsRt = 'Metatarsals [Rt]',
  MetatarsalsLt = 'Metatarsals [Lt]',
  FootPhalangesRt = 'Foot Phalanges [Rt]',
  FootPhalangesLt = 'Foot Phalanges [Lt]',
}

export type BodyPartCategory = BodyMaleFront | BodyMaleBack | BodyFemaleBack | BodyFemaleFront | Skeleton;








