export enum BodyMaleFront {
  Head = 'headMF',
  Neck = 'neckMF',
  Chest = 'chestMF',
  Abdomen = 'abdomenMF',
  Pelvis = 'pelvisMF',
  ShoulderRt = 'shoulderRtMF',
  ShoulderLt = 'shoulderLtMF',
  ArmRt = 'armRtMF',
  ArmLt = 'armLtMF',
  ElbowRt = 'elbowRtMF',
  ElbowLt = 'elbowLtMF',
  ForearmRt = 'forearmRtMF',
  ForearmLt = 'forearmLtMF',
  WristRt = 'wristRtMF',
  WristLt = 'wristLtMF',
  HandRt = 'handRtMF',
  HandLt = 'handLtMF',
  ThighRt = 'thighRtMF',
  ThighLt = 'thighLtMF',
  KneeRt = 'kneeRtMF',
  KneeLt = 'kneeLtMF',
  LegRt = 'legRtMF',
  LegLt = 'legLtMF',
  AnkleRt = 'ankleRtMF',
  AnkleLt = 'ankleLtMF',
  FootRt = 'footRtMF',
  FootLt = 'footLtMF',
}

